//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriOtomasyonu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaleriOtomasyonu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345 {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345__1_ {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345__2_ {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345__3_ {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345 (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345__4_ {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345 (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123_Anywhere_st____any_city__st_12345__5_ {
            get {
                object obj = ResourceManager.GetObject("123 Anywhere st. - any city. st 12345 (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45de476cb72d73a2552ba432fbd6ebea {
            get {
                object obj = ResourceManager.GetObject("45de476cb72d73a2552ba432fbd6ebea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Automotive__Poster__Landscape__ {
            get {
                object obj = ResourceManager.GetObject("Automotive (Poster (Landscape))", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Beige_and_Green_Minimalist_Christmas_Party_Flyer {
            get {
                object obj = ResourceManager.GetObject("Beige and Green Minimalist Christmas Party Flyer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Glitch_Car_Promotion_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Black Glitch Car Promotion Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Illustration_Car_Desktop_Wallpaper {
            get {
                object obj = ResourceManager.GetObject("Black Illustration Car Desktop Wallpaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_White_Minimalist_Car_Rental_Pricelist_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Blue White Minimalist Car Rental Pricelist Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_White_Minimalist_Car_Rental_Pricelist_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("Blue White Minimalist Car Rental Pricelist Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post__2_ {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post__3_ {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post__4_ {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brown_Modern_Car_for_Sale_Instagram_Post__5_ {
            get {
                object obj = ResourceManager.GetObject("Brown Modern Car for Sale Instagram Post (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gradient_Car_Auto_Insurance_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Gradient Car Auto Insurance Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green_Modern_Customer_Testimonials_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Green Modern Customer Testimonials Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grey_Modern_Car_for_Sale_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Grey Modern Car for Sale Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kullanıcıGirişi {
            get {
                object obj = ResourceManager.GetObject("kullanıcıGirişi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modern_Fotoğraf_Araba_Dergi_Kapağı {
            get {
                object obj = ResourceManager.GetObject("Modern Fotoğraf Araba Dergi Kapağı", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Modern_Fotoğraf_Araba_Dergi_Kapağı1 {
            get {
                object obj = ResourceManager.GetObject("Modern Fotoğraf Araba Dergi Kapağı1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap müşteriKaydı {
            get {
                object obj = ResourceManager.GetObject("müşteriKaydı", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_White_Black_Minimalist_Car_Deals_Youtube_Thumbnail {
            get {
                object obj = ResourceManager.GetObject("Red White Black Minimalist Car Deals Youtube Thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_White_Black_Minimalist_Car_Deals_Youtube_Thumbnail__1_ {
            get {
                object obj = ResourceManager.GetObject("Red White Black Minimalist Car Deals Youtube Thumbnail (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Siyah_Çarpıcı_Araç_Kiralama_Afiş {
            get {
                object obj = ResourceManager.GetObject("Siyah Çarpıcı Araç Kiralama Afiş", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_and_Black_Modern_Car_Rent_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Yellow and Black Modern Car Rent Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_and_Black_Modern_Car_Rent_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("Yellow and Black Modern Car Rent Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_and_Blue_Minimalist_Giveaway_For_Member_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Yellow and Blue Minimalist Giveaway For Member Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_and_Blue_Minimalist_Giveaway_For_Member_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("Yellow and Blue Minimalist Giveaway For Member Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yellow_and_Blue_Minimalist_Giveaway_For_Member_Instagram_Post__2_ {
            get {
                object obj = ResourceManager.GetObject("Yellow and Blue Minimalist Giveaway For Member Instagram Post (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
